// Full-length (100-150 word) descriptions for each accessory, keyed by slug.
// Kept separate from src/config/site.js so that file stays a manageable index —
// same pattern as src/content/posts.js for blog bodies.

export const ACCESSORY_BODIES = {
  'bosch-powermore-250-range-extender':
    "The Bosch PowerMore 250Wh Range Extender bolts onto the bottle-cage mounts of compatible Bosch Performance Line and Performance Line CX-powered bikes, adding around 250Wh of extra capacity for longer days out without needing to carry a spare battery or plan a ride around a single charge. It's designed to work alongside the internal PowerTube battery already fitted to your bike, extending typical assisted range by a meaningful margin on higher support settings. Installation is straightforward on any Bosch-compatible frame with the right bottle-cage spacing — check with us before ordering if you're not sure your specific model supports it. A sensible addition for anyone regularly riding longer routes, bikepacking trips, or big vertical days where running out of assistance partway through is a genuine concern, rather than an occasional inconvenience.",

  'bosch-powertube-750-battery':
    "The Bosch PowerTube 750 is a 750Wh internal battery built for Bosch Performance Line and Performance Line CX motor systems, offering the largest standard capacity in Bosch's current PowerTube range. It's the battery to consider if you regularly ride long days with high-assistance settings and want to minimise the chance of running dry before you're home, or if you're upgrading from an older, lower-capacity Bosch battery on a compatible frame. As with any battery upgrade, frame compatibility varies by model and year, so confirm fitment with us before ordering — not every Bosch-powered bike in our range accepts every PowerTube size, and battery compartments differ between manufacturers even on the same motor platform. Genuine Bosch batteries carry the same warranty and safety certification as the battery originally fitted to your bike.",

  'bosch-powertube-500-battery':
    "The Bosch PowerTube 500 is a 500Wh internal battery for Bosch Performance Line and Performance Line CX motor systems — a lighter, more compact alternative to the 750Wh version, and the capacity fitted as standard on several bikes across our range. It suits riders who want a genuine Bosch replacement battery, a spare for a second bike sharing the same frame standard, or a lighter-weight option where outright range matters less than shaving grams off the total bike weight. Fitment depends on your specific frame's battery compartment, so check compatibility with us before ordering — Bosch's PowerTube range isn't universally interchangeable across every model year or frame manufacturer. Comes with the same manufacturer warranty and safety testing as batteries supplied with a new bike.",

  'shimano-bt-e8036-630wh-battery':
    "The Shimano BT-E8036 is a 630Wh internal battery built for Shimano EP8 and EP801 motor systems, matching the capacity used across several Shimano-powered bikes in our range. It's a sensible option if you're replacing an ageing battery, want a genuine spare for a bike you rely on heavily, or are upgrading from a smaller capacity on a frame that accepts the larger unit. Shimano's battery and motor systems are tightly integrated, so always confirm your specific frame and motor generation support the BT-E8036 before ordering — not every EP8/EP801 frame uses the same battery mount, capacity or connector standard. Backed by Shimano's standard battery warranty, matching what you'd get on a new Shimano-powered bike from any of the brands we stock.",

  'dji-avinox-800wh-battery':
    "The DJI Avinox 800Wh Battery is the internal battery built for DJI's Avinox motor system, currently used exclusively across our Amflow PL Carbon and PX Carbon range. At 800Wh, it's a genuinely large-capacity battery suited to longer rides on full assistance, and a sensible spare or replacement for existing Amflow owners. As with the wider Avinox platform, this is a newer entrant to the market compared to established Bosch or Shimano batteries, so UK spare-parts lead times are worth checking with us directly before ordering, particularly if you need a replacement urgently rather than as a planned spare. It carries DJI's standard battery warranty and is designed as a like-for-like replacement or upgrade for the battery originally fitted to your Amflow.",

  'fazua-ride-60-battery':
    "The Fazua Ride 60 Battery is the removable battery unit built for Fazua's Ride 60 lightweight motor system. It's worth being upfront: no bike in our current range uses a Fazua motor, so this listing is here for riders who've bought a Fazua-equipped bike elsewhere and need a genuine replacement or spare battery, rather than as an accessory for anything we stock ourselves. If you're in this position, get in touch before ordering so we can confirm exact compatibility with your specific frame and motor generation, since Fazua's Ride 60 system has gone through more than one battery revision over its production run. We're happy to help source the right unit even for a bike bought elsewhere, and will always tell you honestly if we can't confirm a fit.",

  'bosch-4a-fast-charger':
    "The Bosch 4A Fast Charger is a genuine Bosch charging unit for Performance Line and Performance Line CX battery systems, charging significantly faster than the standard 2A charger supplied with most bikes — useful if you ride frequently and don't want to wait overnight between rides. It's compatible with the full range of Bosch PowerTube and frame-integrated batteries used across our Bosch-powered bikes. A sensible upgrade for anyone charging daily, or a practical spare to keep at a second location — garage, workplace, holiday home — so you're never caught without a charger when you need one. Comes with the same safety certification and manufacturer warranty as the charger supplied with a new Bosch-powered bike.",

  'bosch-2a-compact-charger':
    "The Bosch 2A Compact Charger is the standard charging unit supplied with most Bosch Performance Line and Performance Line CX-powered bikes — smaller and lighter than the 4A fast charger, making it a practical choice for travel or as a genuine spare to keep at a second location. Charging takes longer than the 4A version, but for most riders topping up overnight, that's not a practical downside worth paying extra to avoid. Compatible with the full range of Bosch PowerTube batteries used across our range. A sensible pickup if your original charger has been lost or damaged, or you simply want a spare for convenience without paying extra for fast-charging speed you don't necessarily need day to day.",

  'shimano-steps-charger-ec-e6002':
    "The Shimano STEPS Charger EC-E6002 is the genuine charging unit for Shimano EP8 and EP801 battery systems, matching the charger originally supplied with Shimano-powered bikes across our range. It's a straightforward, compact charger suited to home charging or as a spare kept at a second location so you're never without one when you need to top up. Compatible with Shimano's current-generation EP8-series batteries — always double check your specific battery model before ordering, since Shimano has revised its charging connector across different motor generations over the years. Comes with the same manufacturer warranty and safety certification you'd get with a new Shimano-powered bike bought directly from us.",

  'dji-avinox-fast-charger':
    "The DJI Avinox Fast Charger is the genuine charging unit for DJI's Avinox battery system, currently used across our Amflow PL Carbon and PX Carbon range. It's built to charge the Avinox 800Wh battery efficiently, and makes a sensible spare for Amflow owners who want a charger at a second location or as backup against losing or damaging the original unit supplied with the bike. As with the rest of the Avinox platform, it's a newer product with a shorter UK track record than established Bosch or Shimano chargers — check current stock and lead times with us directly if you need a replacement quickly rather than as a planned spare purchase.",

  'bosch-kiox-300-display':
    "The Bosch Kiox 300 is a colour handlebar display for Bosch's Smart System, showing real-time ride data — speed, assistance level, battery percentage and remaining range — at a glance. It's compatible with Bosch's Smart System-enabled Performance Line CX motors and pairs with the Bosch Flow app for ride tracking and navigation. A genuine upgrade over the more basic Purion 200 display for riders who want fuller data at a glance, including turn-by-turn navigation on supported routes and ride analytics after the fact. Fitment depends on your bike's specific Bosch motor generation — check compatibility with us before ordering, since older Bosch systems use a different display connector and either need an adapter or won't support the Kiox 300 at all.",

  'bosch-purion-200-display':
    "The Bosch Purion 200 is a compact, no-frills handlebar display for Bosch Performance Line and Performance Line CX motor systems, showing core ride data — speed, assistance level and battery status — without the fuller feature set of the Kiox 300. It's a sensible choice if you want a simple, durable display without navigation or smartphone pairing, or if you're replacing a damaged original unit on a compatible Bosch-powered bike. As with any Bosch display upgrade, check your motor generation and mount type with us before ordering, since Bosch's display connectors aren't universally interchangeable across every model year or motor generation we stock across the range.",

  'shimano-sc-em800-display':
    "The Shimano SC-EM800 is a compact handlebar display for Shimano EP8 and EP801 motor systems, showing speed, assistance level and remaining battery at a glance, and pairing with Shimano's E-TUBE app for ride data and firmware updates. It's a genuine replacement or upgrade option for Shimano-powered bikes in our range, and a sensible pickup if your original display is lost or damaged during a crash or general wear. Confirm your specific motor generation with us before ordering, since Shimano's display connectors and mounting hardware have changed across different EP8/EP801 revisions, and not every display fits every frame and motor combination without additional wiring or an adapter.",

  'bosch-performance-line-cx-motor-unit':
    "The Bosch Performance Line CX Motor Unit is a genuine replacement motor for bikes built around Bosch's Performance Line CX platform — the most widely used motor across our range. This is a specialist part best fitted by an authorised Bosch service centre rather than at home, given the precision required to correctly seat, torque and calibrate a replacement motor unit. It's worth contacting us before ordering to confirm your exact frame and motor generation are compatible, since Bosch has revised the Performance Line CX motor across several hardware generations that aren't all interchangeable with each other. Comes with Bosch's standard motor warranty when fitted by an authorised dealer, giving the same peace of mind as the motor originally supplied with your bike.",

  'ebike-torque-arm-kit':
    "An eBike Torque Arm Kit adds extra reinforcement at the rear dropout of hub-motor e-bikes, helping prevent the wheel from spinning loose under the strong torque a mid-drive or hub motor can apply — a genuinely worthwhile addition for riders who tow trailers, carry heavy loads, or simply want extra peace of mind on a bike that sees hard use. It's a universal-fit kit designed to work across most standard dropout widths, though it's worth checking your specific frame's dropout spacing before ordering to be sure of a proper fit before installation. A low-cost, sensible addition for anyone concerned about long-term wear at the rear axle on a heavily used eMTB, and cheap insurance against a more expensive dropout repair down the line.",

  'mtb-full-face-helmet':
    "A proper full-face helmet is the sensible choice for riders tackling enduro, bike-park or genuinely technical descents, where the extra chin and jaw protection over an open-face helmet meaningfully reduces injury risk in a fall. This model is trail and enduro-rated, with ventilation designed for the sustained effort of pedalling uphill on an eMTB rather than the shuttle-and-descend pattern of a dedicated downhill helmet, making it a practical crossover option for e-enduro riders who both climb and descend on the same ride. Fit varies between brands, so we'd recommend trying one on or checking the manufacturer's size chart against your head circumference before ordering, since a poorly fitted helmet is meaningfully less protective regardless of its stated safety rating.",

  'mtb-trail-helmet':
    "An open-face trail helmet is the right choice for the vast majority of UK trail-centre riding, offering solid impact protection without the weight, heat and reduced visibility of a full-face lid. It's a sensible everyday helmet for hardtail and trail-travel full-suspension eMTB riders who aren't regularly tackling genuinely technical, high-consequence descents on a weekly basis. Look for a model with a well-ventilated shell and an adjustable retention system for a secure, comfortable fit across a full day's riding, whatever the weather. As with any helmet, check the manufacturer's size chart against your head circumference before ordering — a correctly fitted helmet matters more for genuine protection than any other single spec on the box.",

  'mtb-knee-elbow-pad-set':
    "A knee and elbow pad set adds a meaningful layer of protection for riders tackling rockier, more technical trails, or anyone building confidence on new terrain who wants a safety margin while pushing their limits. This set is designed for trail and enduro riding — substantial enough to genuinely protect in a fall, without the bulk of dedicated bike-park armour that can restrict movement on longer pedal-heavy rides where mobility matters. Sizing varies by brand, so check the manufacturer's measurements against your own before ordering, since a loose-fitting pad set can shift out of position exactly when you need it most. A sensible addition for any rider spending more time on genuinely technical, rocky UK trail-centre terrain this season.",

  'mtb-gloves':
    "A good pair of MTB gloves protects your hands in a fall, improves grip on the bars in wet UK conditions, and reduces vibration fatigue on longer rides across rough terrain. This pair is designed for trail and enduro riding, with padded palms and a breathable back for comfort across a full day out, whatever the weather throws at you. Sizing runs true to most glove size charts, but it's worth checking the manufacturer's measurements against your own hand size before ordering, since a glove that's too loose can reduce grip and control exactly when precision matters most on technical, root-strewn terrain. A low-cost addition that makes a genuine difference to comfort and control on every single ride.",

  'ebike-rated-lock':
    "An eBike-rated lock is built with a higher security rating than a standard bike lock, reflecting the higher resale value and target-attractiveness of an eMTB compared to an unassisted bike of similar age. This model is Sold Secure or equivalent rated for genuine security rather than a token deterrent, and sized to fit through a wheel and frame simultaneously on most eMTB models in our range. Worth pairing with a secondary cable lock for the front wheel if you're leaving your bike unattended for any length of time, since no single lock is fully theft-proof on its own. A sensible investment given how much more an eMTB typically costs to replace than an unassisted equivalent bike.",

  'torque-wrench-set':
    "A carbon-safe torque wrench set lets you tighten bolts to the exact specification stated by your bike's manufacturer, rather than guessing by feel — essential for carbon frames and components, where over-tightening can crack material that shows no warning signs before it fails catastrophically mid-ride. This set covers the common bolt sizes and torque ranges used across stems, seat clamps, brake mounts and most other adjustable fittings on a modern eMTB, whatever brand you ride. A worthwhile investment for anyone who services their own bike at home, and genuinely cheap insurance against an expensive carbon component failure caused by over-tightening with a standard, unmarked hex key instead of a calibrated tool.",

  'chain-wear-indicator-tool':
    "A chain wear indicator tool measures chain elongation in seconds, telling you exactly when to replace your chain before it starts accelerating wear on your cassette and chainring — parts that cost considerably more to replace than the chain itself if left too long. This is especially relevant on an eMTB, where motor-assisted torque puts more sustained load through the drivetrain than an unassisted bike, meaning chains typically wear faster and are worth checking more regularly than you might expect. A genuinely inexpensive tool that can save a meaningful amount in avoided cassette and chainring replacements over the working life of your bike, and takes seconds to use once you're in the habit of checking.",

  'emtb-cleaning-kit':
    "An eMTB cleaning kit is formulated to clean drivetrain grime and trail dirt without the degreasers and harsh solvents found in some standard bike cleaners, which can degrade the seals around a mid-drive motor and battery compartment over time if used repeatedly. Regular cleaning after wet, muddy rides genuinely extends the life of your drivetrain, brakes and motor seals, and is one of the cheapest, most effective things you can do to protect your investment in an eMTB beyond the purchase price itself. This kit includes the brushes and cleaner needed for a full wash, safe to use around motor and battery housings when used as directed on the packaging.",

  'mtb-puncture-repair-kit':
    "A puncture repair kit rated for eMTB tyres includes the tools and patches suited to the wider, tougher tyre carcasses typically fitted to electric mountain bikes, which can differ meaningfully from a standard road or hybrid bike repair kit in both patch size and tyre lever strength required. Worth carrying on every ride, particularly further from home — a genuine mid-trail puncture on an eMTB is heavier and harder to push back than on an unassisted bike, making a reliable repair kit more valuable than ever when you need it. Compact enough to fit in a jersey pocket, hip pack or frame bag without adding meaningful weight to your ride or getting in the way.",

  'schwalbe-magic-mary-evo':
    "The Schwalbe Magic Mary Evo is an aggressive, e-bike-rated tyre designed for maximum grip on loose, technical terrain — a favoured choice among enduro and gravity riders for its cornering confidence on demanding descents in wet or loose UK conditions. The e-bike-rated Evo casing is reinforced to handle the extra torque and weight of an eMTB compared to the standard version, reducing the risk of sidewall damage or unexpected flats under sustained motor-assisted load. Best suited to riders prioritising outright grip and descending confidence over outright rolling efficiency — expect a small efficiency trade-off on smoother climbs and fire roads in exchange for genuinely excellent control on rough, technical trails when it matters most.",

  'schwalbe-nobby-nic-evo':
    "The Schwalbe Nobby Nic Evo is a versatile trail tyre balancing grip and rolling efficiency, making it a strong all-rounder for UK trail-centre riding rather than a specialist tuned for one specific condition alone. The e-bike-rated Evo casing handles the extra torque and weight of an eMTB better than the standard version, reducing puncture risk under sustained motor-assisted load on rougher ground. A sensible choice for riders who want one tyre that performs reasonably well across mixed terrain — hardpack, loose-over-hard and light mud — rather than optimising heavily for one specific trail condition at the expense of everything else, which suits most weekly trail-centre laps better than a specialist tyre would.",

  'maxxis-minion-dhf-dhr':
    "The Maxxis Minion DHF and DHR is a proven front-and-rear tyre pairing built for aggressive trail and enduro riding, with the DHF's directional tread optimised for front-wheel cornering grip and the DHR's more braking-focused pattern suited to the rear wheel's different demands. Both are available in e-bike-rated casings, reinforced to handle the extra torque and weight eMTBs put through their tyres compared to an unassisted bike on the same trail. A well-regarded pairing among enduro and gravity riders specifically for its predictable, confidence-inspiring grip on varied UK trail-centre terrain, from hardpack through to loose-over-rock sections where front and rear tyres genuinely benefit from different tread patterns rather than a matched pair.",

  'emtb-rated-bike-rack':
    "An eMTB-rated bike rack is built to carry the significantly heavier weight of an electric mountain bike safely — typically rated well beyond the weight limits of a standard unassisted-bike rack, which can fail or damage your bike if used beyond its intended capacity. This model mounts to a tow bar for stable transport of one or more heavy eMTBs, with a wider wheel cradle and stronger frame clamp than a standard rack designed for lighter, unassisted bikes. Worth checking your specific eMTB's weight — commonly 22-27kg depending on model — against the rack's stated capacity before buying, particularly if transporting more than one bike at a time on the same rack simultaneously.",

  'waterproof-emtb-bike-cover':
    "A waterproof eMTB bike cover protects your bike from rain, UV and general weather when stored outdoors or left on a car rack between rides — genuinely useful given how much more an eMTB costs to replace or repair than an unassisted bike if left exposed to the elements long-term without proper cover. This cover is sized generously to fit over a full-suspension eMTB including mirrors, racks and other protruding components, with a design that allows some airflow to reduce condensation build-up underneath rather than trapping damp air against the frame and components. A low-cost way to protect a significant investment if you don't have covered storage at home or work.",

  'frame-top-tube-bag':
    "A frame or top-tube bag adds practical on-bike storage for tools, a phone, snacks or a spare tube, without the bulk of a backpack — useful for longer rides where you want quick access to essentials without stopping to dig through a pack every time you need something. This bag mounts to the frame's top tube or main triangle using adjustable straps, designed to fit securely without excessive rattling or rubbing on the frame during rough descents where a poorly fitted bag can become a genuine annoyance. A practical, low-cost addition for any rider who wants better organisation on the bike itself rather than relying entirely on a backpack for every single ride.",

  'front-rear-light-set':
    "A trail-rated front and rear light set is worth carrying even for daytime rides — dense woodland trail centres can be considerably darker under tree cover than open ground, and a bright, visible light improves both your own vision and your visibility to other trail users sharing the same paths. This set includes a genuinely bright front light suited to riding rather than just being seen, plus a rear light for visibility on shared-use sections or approach roads to and from the trailhead. Battery life varies by brightness setting, so check the runtime at your preferred setting before a long ride to avoid running out of charge partway through, particularly on shorter winter days.",

  'emtb-baggy-shorts':
    "eMTB baggy shorts are cut for the pedalling and body position of trail and enduro riding, with a relaxed fit over an integrated or separate padded liner, and durable, often stretch-panelled fabric that moves with you through a full pedal stroke rather than restricting movement. Multiple pockets are sized for a phone, keys or snacks without bouncing around on rougher descents where a poorly designed pocket can become a genuine distraction. Sizing varies by brand, so check the manufacturer's waist measurements against your own before ordering — baggy shorts are cut generously by design, but fit still varies meaningfully between brands and even between different models from the same manufacturer.",

  'mtb-jersey':
    "An MTB jersey is cut looser than a road cycling jersey, with a relaxed fit that suits the more upright riding position and varied body movement of trail and enduro riding, plus a breathable, moisture-wicking fabric suited to the sustained effort of climbing on an eMTB in variable UK weather. Most feature a longer rear hem for coverage in a more upright riding position and simple pocket storage for small essentials you want quick access to mid-ride. Sizing runs close to standard clothing sizes rather than the tighter fit of road cycling jerseys, but check the specific manufacturer's size chart before ordering since cut and fit varies noticeably between different brands.",
};
