export const REVIEW_STATS = {
  trustScore: 4.8,
  totalReviews: 2418,
  ratingLabel: 'Excellent',
  starsCount: 5,
  distribution: [
    { stars: 5, percentage: 88, count: 2128 },
    { stars: 4, percentage: 8, count: 193 },
    { stars: 3, percentage: 2, count: 48 },
    { stars: 2, percentage: 1, count: 24 },
    { stars: 1, percentage: 1, count: 25 },
  ],
  categories: [
    { id: 'all', label: 'All Reviews', count: 2418 },
    { id: 'delivery', label: 'Delivery & Unboxing', count: 864 },
    { id: 'quality', label: 'Product Quality & eMTB Build', count: 912 },
    { id: 'service', label: 'Customer Service & Advice', count: 420 },
    { id: 'followup', label: 'Post-Purchase Support', count: 222 },
  ],
};

export const REVIEWS = [
  {
    id: 'rev-1',
    author: 'Callum MacLeod',
    location: 'Inverness, Scottish Highlands',
    stars: 5,
    date: '2 days ago',
    verified: true,
    category: 'delivery',
    product: 'Cube Stereo Hybrid 140 HPC SLX 750',
    title: 'Flawless pallet delivery up to the Highlands & ready to ride',
    body: 'Living in Inverness, big bike deliveries are usually a nightmare with couriers. Peak Pedal dispatched on a dedicated pallet, fully boxed with zero damage. The bike came 95% pre-assembled — just straightened the bars, set tire pressures, and charged the Bosch 750Wh battery. Did 35km up the Great Glen trails yesterday and the Bosch CX motor is incredible.',
    helpfulCount: 42,
    response: {
      author: 'Peak Pedal Team',
      date: '1 day ago',
      body: 'Thanks Callum! We make sure all our Highland freight is pallet-strapped so high-end carbon eMTBs arrive in showroom condition. Enjoy the Great Glen trails!',
    },
  },
  {
    id: 'rev-2',
    author: 'Marcus Hensley',
    location: 'Sheffield, Peak District',
    stars: 5,
    date: '4 days ago',
    verified: true,
    category: 'quality',
    product: 'Trek Rail 9.8 XT Gen 4',
    title: 'The Bosch Smart System & carbon frame blew my expectations away',
    body: 'Stepping up from an analogue trail bike to the Trek Rail 9.8 was a big decision. The Peak Pedal team walked me through sizing over WhatsApp video and helped me pick the right frame size (L). The Fox 38 fork and Bosch CX motor turn steep Peak District technical climbs into pure fun. Genuine UK stock with full manufacturer warranty registered.',
    helpfulCount: 38,
  },
  {
    id: 'rev-3',
    author: 'Dr. Sarah Jenkins',
    location: 'Surrey Hills, Guildford',
    stars: 5,
    date: '1 week ago',
    verified: true,
    category: 'service',
    product: 'Specialized Turbo Levo SL Comp Carbon',
    title: 'Honest advice on Lightweight SL vs Full-Power eMTB',
    body: 'I was torn between a heavy 25kg full-power eMTB and a lightweight SL. The advisor at Peak Pedal spent 25 minutes explaining motor torque curves and natural pedal feel. I chose the Levo SL and it handles exactly like an acoustic enduro bike on flowing singletrack. Cannot fault their customer service!',
    helpfulCount: 29,
    response: {
      author: 'Peak Pedal Team',
      date: '6 days ago',
      body: 'Delighted to hear this Sarah! The Levo SL is an absolute weapon on Surrey Hills singletrack. Thanks for trusting our advice.',
    },
  },
  {
    id: 'rev-4',
    author: 'Gareth Evans',
    location: 'Betws-y-Coed, Snowdonia',
    stars: 5,
    date: '1 week ago',
    verified: true,
    category: 'followup',
    product: 'Orbea Wild M-Team 750Wh',
    title: 'Outstanding post-purchase follow-up for suspension setup',
    body: 'Three days after delivery, Mark from technical support reached out to check how the sag and rebound setup was feeling. He gave me baseline damper settings for the Fox Float X2 based on my rider weight and gear. That level of aftercare is practically unheard of with online bike shops.',
    helpfulCount: 34,
  },
  {
    id: 'rev-5',
    author: 'David Thorne',
    location: 'Bristol, Somerset',
    stars: 4,
    date: '2 weeks ago',
    verified: true,
    category: 'delivery',
    product: 'Whyte E-160 RSX 29er',
    title: 'Brilliant bike, delivery courier had a 1-day delay but kept informed',
    body: 'The Whyte E-160 is a masterclass in UK trail geometry — low center of gravity and planted in the mud. Took off 1 star only because DX Freight rescheduled delivery from Thursday to Friday afternoon. Peak Pedal kept me updated throughout and even refunded the priority delivery fee without me asking.',
    helpfulCount: 21,
    response: {
      author: 'Peak Pedal Team',
      date: '2 weeks ago',
      body: 'Hi David, thanks for your fair feedback. We always step in directly when regional courier routes get congested to ensure you’re never left in the dark. Enjoy the Mendip trails!',
    },
  },
  {
    id: 'rev-6',
    author: 'Richard Bellingham',
    location: 'Kendal, Lake District',
    stars: 5,
    date: '2 weeks ago',
    verified: true,
    category: 'quality',
    product: 'Santa Cruz Heckler CC MX X0 AXS',
    title: 'Premium build quality & seamless wireless shifting',
    body: 'Ordered the Santa Cruz Heckler MX. It arrived with SRAM AXS already paired and firmware updated. Pre-delivery inspection sheet included with torque check signatures. Rode Grizedale forest all weekend on a single charge. 10/10 shopping experience.',
    helpfulCount: 19,
  },
  {
    id: 'rev-7',
    author: 'Liam O’Connor',
    location: 'Belfast, Northern Ireland',
    stars: 4,
    date: '3 weeks ago',
    verified: true,
    category: 'service',
    product: 'Amflow PL Carbon Pro (DJI Avinox)',
    title: 'Cutting-edge DJI Avinox motor, great tech support on app pairing',
    body: 'Was skeptical about ordering the new DJI Avinox motor platform, but Peak Pedal are authorized specialists. Had a minor hiccup binding the Avinox app with my UK phone number on day one, but their support staff responded via WhatsApp in 10 minutes with the exact step-by-step fix.',
    helpfulCount: 17,
  },
  {
    id: 'rev-8',
    author: 'Simon Bradley',
    location: 'Bakewell, Peak District',
    stars: 3,
    date: '3 weeks ago',
    verified: true,
    category: 'followup',
    product: 'Bosch PowerTube 750Wh Battery & 4A Charger',
    title: 'Genuine Bosch battery, delivery driver left box in porch without ringing',
    body: 'Product itself is 100% genuine Bosch with UK plug and serial security seal intact. However the courier driver left the parcel in the open porch without ringing the doorbell. Contacted Peak Pedal customer service who escalated a complaint to the courier depot manager.',
    helpfulCount: 14,
    response: {
      author: 'Peak Pedal Team',
      date: '3 weeks ago',
      body: 'Hi Simon, we deeply apologize for the courier’s carelessness with your battery delivery. We have filed a formal driver breach with the courier management and updated delivery instructions on your account for future orders.',
    },
  },
  {
    id: 'rev-9',
    author: 'Heather Wilkinson',
    location: 'Harrogate, Yorkshire',
    stars: 5,
    date: '4 weeks ago',
    verified: true,
    category: 'quality',
    product: 'Mondraker Crafty Carbon RR',
    title: 'Forward Geometry makes steep descents feel so confidence inspiring',
    body: 'I upgraded from a 2019 hardtail and was nervous about the slack head angle. The Mondraker Crafty is an absolute dream. Peak Pedal included tubeless valves, sealant, and a shock pump in the welcome pack. Top-tier service from start to finish.',
    helpfulCount: 26,
  },
  {
    id: 'rev-10',
    author: 'Nigel Campbell',
    location: 'Fort William, Scotland',
    stars: 2,
    date: '1 month ago',
    verified: true,
    category: 'delivery',
    product: 'Transition Repeater PT Carbon',
    title: 'Initial box had a puncture during transit — resolved swiftly with replacement parts',
    body: 'The outer cardboard box arrived with a puncture hole that scratched the non-drive chainstay during freight transit. I was initially very frustrated given the price tag. However, Peak Pedal customer care was exemplary — they arranged a technician inspection, covered paint touch-up and sent a complimentary set of Muc-Off tubeless protection kit. Appreciate the swift accountability.',
    helpfulCount: 31,
    response: {
      author: 'Peak Pedal Team',
      date: '1 month ago',
      body: 'Thank you Nigel. Freight incidents are rare but when they happen we take 100% responsibility immediately so you are never out of pocket. We appreciate your patience while our tech team resolved it.',
    },
  },
  {
    id: 'rev-11',
    author: 'Tom Fairclough',
    location: 'Stroud, Gloucestershire',
    stars: 5,
    date: '1 month ago',
    verified: true,
    category: 'service',
    product: 'Merida eOne-Sixty 875',
    title: 'Cycle to Work scheme processed quickly with zero fuss',
    body: 'Processed my Merida through the Green Commute Initiative scheme. Peak Pedal issued the quotation within an hour, coordinated with my employer’s HR portal, and bike was dispatched as soon as the voucher was redeemed. Effortless process.',
    helpfulCount: 22,
  },
  {
    id: 'rev-12',
    author: 'Pauline Davies',
    location: 'Cardiff, Wales',
    stars: 5,
    date: '1 month ago',
    verified: true,
    category: 'quality',
    product: 'Cube Reaction Hybrid Pro 750',
    title: 'Perfect hardtail for gravel tracks & trail centres alike',
    body: 'Bought for riding the Taff Trail and Afan Forest. The bike is smooth, quiet, and battery easily lasts 60+ miles on Tour mode. Very happy with Peak Pedal’s communication and packaging.',
    helpfulCount: 16,
  },
];
